version: '3.8'

services:
  backend:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - db

  db:
    build:
      context: ../docker
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: